<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5f1720f72023c',
        'title' => 'About the course',
        'fields' => array(
            array(
                'key' => 'field_5f1720f93b0ef',
                'label' => 'What will people learn?',
                'name' => 'description',
                'type' => 'textarea',
                'instructions' => 'Write a few clear, succinct sentences about the course syllabus. Try to list at least three things.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
            ),
            array(
                'key' => 'field_5f1729d4731c5',
                'label' => 'Is there a pre-course assessment?',
                'name' => 'pre_course_assessment',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5f1729e4731c6',
                'label' => 'Is the course delivered online or in person?',
                'name' => 'delivered_online',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'true' => 'Mostly online',
                    'false' => 'Mostly in person',
                ),
                'allow_null' => 0,
                'default_value' => 'true',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5f172aac448b7',
                'label' => 'Which online tool is used?',
                'name' => 'online_tool',
                'type' => 'radio',
                'instructions' => 'So we can provide specific joining instructions to the learner.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f1729e4731c6',
                            'operator' => '==',
                            'value' => 'true',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Microsoft Teams' => 'Microsoft Teams',
                    'Google Hangouts' => 'Google Hangouts',
                    'Zoom' => 'Zoom',
                    'false' => 'Something else',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5f172b9da858a',
                'label' => 'Venue',
                'name' => 'venue',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f1729e4731c6',
                            'operator' => '==',
                            'value' => 'false',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f172aeb85fa2',
                        'label' => 'Location',
                        'name' => 'location',
                        'type' => 'google_map',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'center_lat' => '51.5487941',
                        'center_lng' => '-0.0955383',
                        'zoom' => '',
                        'height' => '',
                    ),
                    array(
                        'key' => 'field_5f172b470ec4a',
                        'label' => 'Venue details',
                        'name' => 'venue_details',
                        'type' => 'textarea',
                        'instructions' => 'In a few sentences, explain the accessibility of the venue or other important details. eg. wheelchair-accessible bathroom, hearing loop, nearby bus stop.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'course',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f172d96c5dfe',
        'title' => 'About the tutor',
        'fields' => array(
            array(
                'key' => 'field_5f172dadc3839',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f172dbbc383a',
                'label' => 'Biography',
                'name' => 'biography',
                'type' => 'textarea',
                'instructions' => 'Give a short biography of the tutor\'s experience and skills in a few sentences.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5f172de3c383b',
                'label' => 'Headshot',
                'name' => 'headshot',
                'type' => 'image',
                'instructions' => 'A professional photograph of the tutor.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'course',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f173125f161f',
        'title' => 'About this intake',
        'fields' => array(
            array(
                'key' => 'field_5f17312b1eba1',
                'label' => 'Parent course',
                'name' => 'parent_course',
                'type' => 'post_object',
                'instructions' => 'Every intake must belong to a course',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'course',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
            ),
            array(
                'key' => 'field_5f1731451eba2',
                'label' => 'Start date',
                'name' => 'start_date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F j, Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5f1731551eba3',
                'label' => 'End date',
                'name' => 'end_date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F j, Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'intake',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f173239d37dc',
        'title' => 'Entry requirements',
        'fields' => array(
            array(
                'key' => 'field_5f17323faf9a7',
                'label' => 'Level',
                'name' => 'level',
                'type' => 'radio',
                'instructions' => 'Which level is this course?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'false' => 'None',
                    1 => '1',
                    2 => '2',
                    3 => '3',
                ),
                'allow_null' => 0,
                'other_choice' => 1,
                'save_other_choice' => 1,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5f17325aaf9a8',
                'label' => 'Entry requirement details',
                'name' => 'entry_requirements',
                'type' => 'textarea',
                'instructions' => 'In a short sentence, explain the specific entry requirements for this course. Don\'t include general entry requirements for all courses.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'intake',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5eda4b5fb6236',
        'title' => 'Hub fields',
        'fields' => array(
            array(
                'key' => 'field_5eda4b697c714',
                'label' => 'Location',
                'name' => 'location',
                'type' => 'google_map',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'center_lat' => '51.5487941',
                'center_lng' => '-0.0955383',
                'zoom' => '',
                'height' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'hub',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f172e2c0c5fe',
        'title' => 'Testimonials',
        'fields' => array(
            array(
                'key' => 'field_5f172e381ec87',
                'label' => '',
                'name' => 'testimonials',
                'type' => 'relationship',
                'instructions' => 'Choose the testimonials you\'d like to appear alongside this course.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'testimonial',
                ),
                'taxonomy' => '',
                'filters' => '',
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'object',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'course',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;