<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5f1720f72023c',
		'title' => 'About the course',
		'fields' => array(
			array(
				'key' => 'field_5f1720f93b0ef',
				'label' => 'What will people learn?',
				'name' => 'description',
				'type' => 'textarea',
				'instructions' => 'Write a few clear, succinct sentences about the course syllabus. Try to list at least three things.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5f1729e4731c6',
				'label' => 'Is the course delivered online or in person?',
				'name' => 'delivery',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'online' => 'Mostly online',
					'person' => 'Mostly in person',
				),
				'allow_null' => 0,
				'default_value' => 'online',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5f172aac448b7',
				'label' => 'Which online tool is used?',
				'name' => 'online_tool',
				'type' => 'radio',
				'instructions' => 'So we can tell the user which platform will be used for their lessons.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f1729e4731c6',
							'operator' => '==',
							'value' => 'online',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Microsoft Teams' => 'Microsoft Teams',
					'Google Meet' => 'Google Meet',
					'Zoom' => 'Zoom',
				),
				'allow_null' => 0,
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5f172b9da858a',
				'label' => 'Venue',
				'name' => 'venue',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f1729e4731c6',
							'operator' => '==',
							'value' => 'person',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5f172aeb85fa2',
						'label' => 'Location',
						'name' => 'location',
						'type' => 'google_map',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'center_lat' => '51.5487941',
						'center_lng' => '-0.0955383',
						'zoom' => '',
						'height' => '',
					),
					array(
						'key' => 'field_5f172b470ec4a',
						'label' => 'Venue details',
						'name' => 'venue_details',
						'type' => 'textarea',
						'instructions' => 'In a few sentences, explain the accessibility of the venue or other important details. eg. wheelchair-accessible bathroom, hearing loop, nearby bus stop.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 2,
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_5f1729d4731c5',
				'label' => 'Is there a pre-course assessment?',
				'name' => 'pre_course_assessment',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5f21649ec7402',
				'label' => 'Is this course accredited by an external organisation?',
				'name' => 'accredited',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5f23450818090',
				'label' => 'Accreditation details',
				'name' => 'accreditation_details',
				'type' => 'textarea',
				'instructions' => 'Explain who accredits this course and how that benefits learners. Will they get a certificate or qualification at the end?',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f21649ec7402',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5f8445483a40f',
				'label' => 'Custom "no intakes" message',
				'name' => 'no_intakes_message',
				'type' => 'wysiwyg',
				'instructions' => 'If this course has no intakes, this fallback message will be shown instead. You can use it to invite people to apply to courses by phone or email.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f6491f1947e1',
		'title' => 'About the event',
		'fields' => array(
			array(
				'key' => 'field_5f649207a9db9',
				'label' => 'Short description',
				'name' => 'description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5f64923ea9dbb',
				'label' => 'Event date',
				'name' => 'event_date',
				'type' => 'date_picker',
				'instructions' => 'When the event takes place',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'return_format' => 'F j, Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5f649513ede6a',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => 'Where is the event held if it is in-person?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f64952f3f579',
				'label' => 'URL',
				'name' => 'external_application_url',
				'type' => 'url',
				'instructions' => 'Link to the event for more details and registration',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5eda4b5fb6236',
		'title' => 'About the hub',
		'fields' => array(
			array(
				'key' => 'field_5eda4b697c714',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '51.5487941',
				'center_lng' => '-0.0955383',
				'zoom' => '',
				'height' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'hub',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f173125f161f',
		'title' => 'About the intake',
		'fields' => array(
			array(
				'key' => 'field_5f17312b1eba1',
				'label' => 'Parent course',
				'name' => 'parent_course',
				'type' => 'post_object',
				'instructions' => 'Every intake must belong to a course',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'course',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5f21835dfbd65',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'instructions' => 'Add any specific details about this intake. Don\'t repeat the general course description.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5f1731451eba2',
				'label' => 'Start date',
				'name' => 'start_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'M j, Y',
				'return_format' => 'M j, Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5f1731551eba3',
				'label' => 'End date',
				'name' => 'end_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'M j, Y',
				'return_format' => 'M j, Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5f1816457c2ca',
				'label' => 'Days',
				'name' => 'days',
				'type' => 'checkbox',
				'instructions' => 'Select what days this will run',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Mondays' => 'Mondays',
					'Tuesdays' => 'Tuesdays',
					'Wednesdays' => 'Wednesdays',
					'Thursdays' => 'Thursdays',
					'Fridays' => 'Fridays',
					'Saturdays' => 'Saturdays',
					'Sundays' => 'Sundays',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5f18180769f30',
				'label' => 'Start time',
				'name' => 'start_time',
				'type' => 'time_picker',
				'instructions' => 'What time does it start?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g.ia',
			),
			array(
				'key' => 'field_5f1818e295287',
				'label' => 'End time',
				'name' => 'end_time',
				'type' => 'time_picker',
				'instructions' => 'What time does it end?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g.ia',
			),
			array(
				'key' => 'field_5f844628def4d',
				'label' => 'How will applications to this intake be managed?',
				'name' => 'management',
				'type' => 'button_group',
				'instructions' => 'Do you want to use the built-in application form, or provide your own?',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'internal' => 'Hackney Council will manage applications',
					'external' => 'I will manage applications myself',
				),
				'allow_null' => 0,
				'default_value' => 'internal',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5f183bde793ab',
				'label' => 'Total capacity',
				'name' => 'total_capacity',
				'type' => 'number',
				'instructions' => 'Not shown to prospective learners, but used to calculate when courses are full.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f844628def4d',
							'operator' => '==',
							'value' => 'internal',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_5f6228bacb211',
				'label' => 'External application URL',
				'name' => 'external_application_url',
				'type' => 'url',
				'instructions' => 'Provide a webpage or mailto: link where people can apply to this course, if applicable.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f844628def4d',
							'operator' => '==',
							'value' => 'external',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'intake',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f172d96c5dfe',
		'title' => 'About the tutor',
		'fields' => array(
			array(
				'key' => 'field_5f22ac662e21f',
				'label' => 'Name',
				'name' => 'tutor_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f22aca7380c8',
				'label' => 'Biography',
				'name' => 'tutor_biography',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5f22acba380c9',
				'label' => 'Headshot',
				'name' => 'tutor_headshot',
				'type' => 'image',
				'instructions' => 'A professional photograph of the tutor.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5f22acda380ca',
				'label' => 'Show tutor information?',
				'name' => 'show_tutor',
				'type' => 'true_false',
				'instructions' => 'Make tutor information visible to prospective learners.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f648cfe5141a',
		'title' => 'About the vacancy',
		'fields' => array(
			array(
				'key' => 'field_5f6490988962b',
				'label' => 'What kind of vacancy is this?',
				'name' => 'vacancy_kind',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Job' => 'Job',
					'Work Placement' => 'Work Placement',
					'Apprenticeship' => 'Apprenticeship',
					'Volunteering' => 'Volunteering',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5f648de3bc199',
				'label' => 'Short description',
				'name' => 'description',
				'type' => 'textarea',
				'instructions' => 'Summarise the vacancy in a short but complete sentence.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5f648e1cbc19a',
				'label' => 'Full description',
				'name' => 'full_description',
				'type' => 'wysiwyg',
				'instructions' => 'Provide full details about this vacancy. If you leave this blank, the short description will be used.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5f648e53bc19b',
				'label' => 'Closing date',
				'name' => 'closing_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5f648ed490203',
				'label' => 'Contract type',
				'name' => 'contract',
				'type' => 'text',
				'instructions' => 'For example, "Permanent" or "Fixed term"',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 25,
			),
			array(
				'key' => 'field_5f648fd090204',
				'label' => 'Hours',
				'name' => 'hours',
				'type' => 'text',
				'instructions' => 'What is the weekly commitment of hours? For example, "16 hours per week".',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 25,
			),
			array(
				'key' => 'field_5f64900e90205',
				'label' => 'Salary',
				'name' => 'salary',
				'type' => 'text',
				'instructions' => 'For example, "£10 per hour" or "£22,000 per year"',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f6490988962b',
							'operator' => '!=',
							'value' => 'Volunteering',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 25,
			),
			array(
				'key' => 'field_5f64971ea7fc5',
				'label' => 'What qualifications does this vacancy need?',
				'name' => 'qualifications',
				'type' => 'text',
				'instructions' => 'For example, "A-level English"',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f6490988962b',
							'operator' => '==',
							'value' => 'Apprenticeship',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => 25,
			),
			array(
				'key' => 'field_5f64919dbfa88',
				'label' => 'Employer',
				'name' => 'employer',
				'type' => 'text',
				'instructions' => 'Which organisation is offering this vacancy? For example, "Hackney Council"',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f73494474999',
				'label' => 'What preparation does this vacancy need?',
				'name' => 'checklist_items',
				'type' => 'relationship',
				'instructions' => 'Attach relevant checklist items to the vacancy. Applicants will have to tick off all of these before applying.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'checklist_item',
				),
				'taxonomy' => '',
				'filters' => '',
				'elements' => '',
				'min' => '',
				'max' => 5,
				'return_format' => 'object',
			),
			array(
				'key' => 'field_5f86f270b4deb',
				'label' => 'How will applications to this vacancy be managed?',
				'name' => 'management',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'internal' => 'Hackney Council will manage applications',
					'external' => 'On an external website',
				),
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5f649745a7fc6',
				'label' => 'External application URL',
				'name' => 'external_application_url',
				'type' => 'url',
				'instructions' => 'If applications for this vacancy are handled on a third-party website, give the URL here. This will OVERRIDE the normal application form.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5f86f270b4deb',
							'operator' => '==',
							'value' => 'external',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'vacancy',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f1f43a27652c',
		'title' => 'Call to action',
		'fields' => array(
			array(
				'key' => 'field_5f1f43a5b22e5',
				'label' => 'Link',
				'name' => 'call_to_action',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_5f1f44e0b1e2b',
				'label' => 'Label',
				'name' => 'call_to_action_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'page-promotional.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f173239d37dc',
		'title' => 'Entry requirements',
		'fields' => array(
			array(
				'key' => 'field_5f17323faf9a7',
				'label' => 'Level',
				'name' => 'level',
				'type' => 'radio',
				'instructions' => 'Which level is this course?',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Level 1' => 'Level 1',
					'Level 2' => 'Level 2',
					'Level 3' => 'Level 3',
					'Entry' => 'Entry',
					'Beginners' => 'Beginners',
					'false' => 'false',
					1 => '1',
					2 => '2',
					'Based on assessment' => 'Based on assessment',
					'Entry 1' => 'Entry 1',
					'Entry 3' => 'Entry 3',
					'Entry 2/3' => 'Entry 2/3',
					'Entry 1 to level 2' => 'Entry 1 to level 2',
					'Entry 2' => 'Entry 2',
				),
				'allow_null' => 0,
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5f17325aaf9a8',
				'label' => 'Details',
				'name' => 'entry_requirements',
				'type' => 'textarea',
				'instructions' => 'In a short sentence, explain the specific entry requirements for this course. Don\'t include general entry requirements for all courses.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => 'wpautop',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f25eda3742a2',
		'title' => 'Extra category information',
		'fields' => array(
			array(
				'key' => 'field_5f3a553522cd7',
				'label' => 'Show as filter?',
				'name' => 'show_as_filter',
				'type' => 'button_group',
				'instructions' => 'Make this taxonomy visible as a filter in the course search. If hidden, the category can still be filtered by URL, but won\'t appear in the interface.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'false' => 'Hide',
					'topic' => 'Show in "Topics"',
					'only' => 'Show in "Only show"',
				),
				'allow_null' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'curriculum_areas',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f8f06d15f8c6',
		'title' => 'Featured',
		'fields' => array(
			array(
				'key' => 'field_5f8f06d85f3c2',
				'label' => 'Feature this opportunity on the homepage?',
				'name' => 'featured',
				'type' => 'true_false',
				'instructions' => 'The three most recent featured opportunities will appear on the homepage',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'vacancy',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f61e5b9a259a',
		'title' => 'Sidebar',
		'fields' => array(
			array(
				'key' => 'field_5f61e5c964fbd',
				'label' => 'Related content',
				'name' => 'related',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'elements' => '',
				'min' => 1,
				'max' => '',
				'return_format' => 'object',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'default',
				),
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5f172e2c0c5fe',
		'title' => 'Testimonials',
		'fields' => array(
			array(
				'key' => 'field_5f172e381ec87',
				'label' => '',
				'name' => 'testimonials',
				'type' => 'relationship',
				'instructions' => 'Choose the testimonials you\'d like to appear alongside this course.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'testimonial',
				),
				'taxonomy' => '',
				'filters' => '',
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;